// Copies the deployed ABIs and addresses (including the payout token) into the web app.
// Usage: pnpm export-abis [deployment-id]
//   monad-v3:            real Agora AUSD, per-payout claim windows, gasless deposits and payouts
//   monad-ausd (default): real Agora AUSD, with the claim verifier (email check)
//   monad-v2:            tAUSD, with the claim verifier
//   monad-test-ausd:     tAUSD, before the verifier (claims need only the link)
//   chain-10143:         real Agora AUSD, before the verifier (redeploy with the verifier for the demo)
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const deploymentId = process.argv[2] ?? "monad-ausd";
const root = join(import.meta.dirname, "..");
const deployment = join(root, "ignition", "deployments", deploymentId);
const out = join(root, "..", "apps", "web", "lib", "fanout", "abis", "contracts.generated.ts");

const contracts = [
  ["treasury", "Treasury"],
  ["batchPayout", "BatchPayout"],
  ["claimEscrow", "ClaimEscrow"],
] as const;

// Keys look like "<ModuleId>#<ContractName>"; the module id differs per deploy module.
const addresses: Record<string, string> = JSON.parse(readFileSync(join(deployment, "deployed_addresses.json"), "utf8"));
const futureId = (name: string) => {
  const id = Object.keys(addresses).find((k) => k.endsWith(`#${name}`));
  if (!id) throw new Error(`No ${name} in ${deploymentId}`);
  return id;
};

// The payout token is whatever Treasury was constructed with.
const journal = readFileSync(join(deployment, "journal.jsonl"), "utf8").trim().split("\n").map((l) => JSON.parse(l));
const treasuryInit = journal.find((e) => e.type === "DEPLOYMENT_EXECUTION_STATE_INITIALIZE" && e.futureId === futureId("Treasury"));
const ausd: string = treasuryInit.constructorArgs[0];

let file = `// GENERATED by smart-contract/scripts/export-abis.ts from ignition/deployments/${deploymentId}. Do not edit.\n`;
file += `// After a redeploy: pnpm --filter smart-contract export-abis [deployment-id]\n\n`;
file += `export const deployment = ${JSON.stringify(deploymentId)};\n\n`;
file += `export const deployedAddresses = ${JSON.stringify(
  { ausd, ...Object.fromEntries(contracts.map(([key, name]) => [key, addresses[futureId(name)]])) },
  null,
  2,
)} as const;\n`;

for (const [key, name] of contracts) {
  const { abi } = JSON.parse(readFileSync(join(deployment, "artifacts", `${futureId(name)}.json`), "utf8"));
  file += `\nexport const ${key}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
}

writeFileSync(out, file);
console.log(`Wrote ${out} from ${deploymentId} (token ${ausd})`);
