// Copies the deployed ABIs and addresses into the web app.
// Usage: pnpm export-abis [deployment-id]   (default: chain-10143)
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const deploymentId = process.argv[2] ?? "chain-10143";
const root = join(import.meta.dirname, "..");
const deployment = join(root, "ignition", "deployments", deploymentId);
const out = join(root, "..", "apps", "web", "lib", "fanout", "abis", "contracts.generated.ts");

const contracts = [
  ["treasury", "Treasury"],
  ["batchPayout", "BatchPayout"],
  ["claimEscrow", "ClaimEscrow"],
] as const;

const addresses: Record<string, string> = JSON.parse(readFileSync(join(deployment, "deployed_addresses.json"), "utf8"));

let file = `// GENERATED by smart-contract/scripts/export-abis.ts from ignition/deployments/${deploymentId}. Do not edit.\n`;
file += `// After a redeploy: pnpm --filter smart-contract export-abis\n\n`;
file += `export const deployedAddresses = ${JSON.stringify(
  Object.fromEntries(contracts.map(([key, name]) => [key, addresses[`Fanout#${name}`]])),
  null,
  2,
)} as const;\n`;

for (const [key, name] of contracts) {
  const { abi } = JSON.parse(readFileSync(join(deployment, "artifacts", `Fanout#${name}.json`), "utf8"));
  file += `\nexport const ${key}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
}

writeFileSync(out, file);
console.log(`Wrote ${out}`);
