// GENERATED by scripts/sync-abis.mjs. Monad testnet (chain 10143) deployment; env vars override these.
export const deployed = {
  treasury: "0x74a8D547daD96f478135E475360d719df1cA2BFa",
  batchPayout: "0x408640A93b9e11C2e7799fd3eB1975b5B7FC10F4",
  claimEscrow: "0x7AB0E50E02e900dc423AAF5858c8E70289B44F11",
} as const;
