// Regenerates lib/fanout/abis/contracts.ts and deployed.ts from the Hardhat Ignition deployment.
// Usage: node scripts/sync-abis.mjs [deploymentDir]
// Default dir: ../../smart-contract/ignition/deployments/chain-10143 (the contracts package).
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const dir = path.resolve(process.argv[2] ?? "../../smart-contract/ignition/deployments/chain-10143");
const artifact = (name) => {
  const direct = path.join(dir, "artifacts", `Fanout#${name}.json`);
  const flat = path.join(dir, `${name}.json`);
  return JSON.parse(readFileSync(existsSync(direct) ? direct : flat, "utf8"));
};

const out = ["// GENERATED by scripts/sync-abis.mjs from the smart-contract deployment. Do not edit by hand.", ""];
for (const [name, exportName] of [["Treasury", "treasuryAbi"], ["BatchPayout", "batchPayoutAbi"], ["ClaimEscrow", "claimEscrowAbi"]]) {
  out.push(`export const ${exportName} = ${JSON.stringify(artifact(name).abi, null, 2)} as const;`, "");
}
writeFileSync("lib/fanout/abis/contracts.ts", out.join("\n"));

const addressesFile = path.join(dir, "deployed_addresses.json");
if (existsSync(addressesFile)) {
  const a = JSON.parse(readFileSync(addressesFile, "utf8"));
  writeFileSync(
    "lib/fanout/abis/deployed.ts",
    [
      "// GENERATED by scripts/sync-abis.mjs. Monad testnet (chain 10143) deployment; env vars override these.",
      "export const deployed = {",
      `  treasury: "${a["Fanout#Treasury"]}",`,
      `  batchPayout: "${a["Fanout#BatchPayout"]}",`,
      `  claimEscrow: "${a["Fanout#ClaimEscrow"]}",`,
      "} as const;",
      "",
    ].join("\n"),
  );
}
console.log(`ABIs written from ${dir}`);
